# ==============================================================================
# ENTORNO DE DESARROLLO PHP + MARIADB + PHPMYADMIN
# ==============================================================================
# Este archivo levanta un stack completo de desarrollo. 
# Las credenciales y configuración se gestionan mediante el archivo .env
# ==============================================================================
services:
# --- MOTOR DE BASE DE DATOS ---
  db:
    image: mariadb:11.8-ubi9-rc 
    restart: unless-stopped # Reinicia el contenedor si se detiene por fallo, pero no si se detiene manualmente
    environment: # Variables de entorno para la configuración de MariaDB
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} # Contraseña del usuario root
      MYSQL_DATABASE: ${MYSQL_DATABASE} # Nombre de la base de datos a crear
      MYSQL_USER: ${MYSQL_USER} # Usuario adicional
      MYSQL_PASSWORD: ${MYSQL_PASSWORD} # Contraseña del usuario adicional
      # PMA_HOST y PMA_PORT se usan en el contenedor de phpmyadmin  
    # env_file:
    #   - .env
    ports:
      - '127.0.0.1:3306:3306' # Mapeo local para herramientas externas
    labels: # Etiquetas para identificar los puertos en herramientas
      - "port.3306=MariaDB" 
    volumes: # Montaje de volumen para persistencia de datos
      - db_data:/var/lib/mysql

  # --- ENTORNO DE DESARROLLO PHP ---

  phpdev:
    build:
      context: .  # Ruta al Dockerfile
      dockerfile: Dockerfile
    volumes: # Montajes de volúmenes
      - ../:/workspaces # Montaje del código fuente en el contenedor
    # - .:/var/www/html
    ports: # Mapeo de puertos
      - '127.0.0.1:80:80' # Puerto para la aplicación web
      - '127.0.0.1:9000:9000' # Puerto para Xdebug (versión anterior a Xdebug 3)
      - '127.0.0.1:9003:9003' # Puerto para Xdebug (Xdebug 3)
    labels:
      - "port.80=App Web"
      - "port.9000=Xdebug"
      - "port.9003=Xdebug3"
    depends_on: # Dependencias de servicio
      - db # Asegura que la base de datos esté disponible antes de iniciar PHP

# --- ADMINISTRACIÓN DE BD (OPCIONAL) ---
  phpmyadmin:
    image: phpmyadmin:5.2.2-apache
    restart: unless-stopped
    environment:
      PMA_HOST: ${PMA_HOST}
      PMA_PORT: ${PMA_PORT}
      # Aprovecho y uso las mismas variables de entorno que el contenedor de la BD
      # CUIDADO AQUI
      # Poner root para tener todos los privilegios, y que mariadb no ponga problemas con el nombre de user
      # si lo dejo del otro modo da problemas luego al abrir phpmyadmin, porque provoca
      # confusion con lo que tengo configurado en el .env
      # PMA_USER: root
      # si tienes claro que user va y lo tienes bien configurado en el .env puedes usarlo. Pero OJO
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - '127.0.0.1:8080:80' # 80 del contenedor al puerto 8080 del host
    labels:
      - "port.8080=PhpMyAdmin"
    depends_on:
      - db
    # profiles: ["phpmyadmin"] #POr si quiero lanzar a mano
    # env_file:
    #   - .env
    # Esta línea la uso para habilitar o deshabilitar phpMyAdmin 
    # 1 para habilitar, 0 para deshabilitar. POr defecto cero
    # Tengo que cambiarlo en el archivo .env
    deploy:
      replicas: ${ENABLE_PHPMYADMIN:-0}

volumes:
  db_data: