version: '3.1'
services:
  phpimw:
    build:
      context: .
      dockerfile: Dockerfile

    expose:
      - 80

    ports:
      - '8888:80'

    volumes:
      - ../..:/workspaces
      
    extra_hosts:
      - "host.docker.internal:host-gateway"