version: '3.1'
services:
  phpdev:
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"

    build:
      context: .
      dockerfile: Dockerfile
    hostname: phpdev

    expose:
      - '127.0.0.1:80:80'
      - '127.0.0.1:8080:80'
      # Para Xdebug
      - '127.0.0.1:9000:9000'
      - '127.0.0.1:9003:9003'
    
    ports:
      - '127.0.0.1:80:80'
      - '127.0.0.1:8080:80'
      # Para Xdebug
      - '127.0.0.1:9000:9000'
      - '127.0.0.1:9003:9003'

    volumes:
      - ../:/workspaces

