zend_extension=xdebug
xdebug.mode=debug
xdebug.start_with_request=trigger
xdebug.log=/var/log/apache2/xdebug.log
xdebug.max_nesting_level = -1
xdebug.client_port=9003
#xdebug.client_host=${HOST_IP}
xdebug.client_host=host.docker.internal
