# docker/php/xdebug.ini
zend_extension=xdebug

[xdebug]
xdebug.mode=debug
xdebug.start_with_request=yes
xdebug.client_port=9003
xdebug.client_host='host.docker.internal'




xdebug.mode=debug
xdebug.idekey=docker
xdebug.start_with_request=yes
#xdebug.start_with_request=trigger
xdebug.log=/var/log/apache2/xdebug.log
xdebug.max_nesting_level = -1
xdebug.client_port=9003
#xdebug.client_host=${HOST_IP}
xdebug.client_host='host.docker.internal'


-----
zend_extension=xdebug
xdebug.mode=debug
xdebug.idekey=VSCODE
xdebug.log=/var/log/apache2/xdebug.log
xdebug.client_port=9003
xdebug.client_host=host.docker.internal

---- EMILIO
zend_extension=xdebug
xdebug.mode=debug
xdebug.start_with_request=trigger
xdebug.log=/var/log/apache2/xdebug.log
xdebug.max_nesting_level = -1
xdebug.client_port=9003
#xdebug.client_host=${HOST_IP}
xdebug.client_host=host.docker.internal

------ CORRECTILLO
#docker-php-ext-xdebug.ini
zend_extension=xdebug

[xdebug]
xdebug.mode=debug
# xdebug.idekey=vscode
xdebug.start_with_request=yes
#xdebug.start_with_request=trigger
xdebug.log=/var/log/apache2/xdebug.log
#xdebug.max_nesting_level = -1
xdebug.client_port=9003
#xdebug.client_host=${HOST_IP}
#xdebug.client_host='host.docker.internal'
#xdebug.client_host=127.0.0.1
xdebug.client_host=172.19.0.2